# Generated by Django 3.1.1 on 2020-10-06 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('trigger', models.TextField(max_length=200)),
                ('routine', models.TextField(max_length=200)),
                ('reward', models.TextField(max_length=200)),
                ('good', models.BooleanField()),
            ],
        ),
    ]
